import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'

import ProfileImage from '@/public/profile2.png'


interface Props {
  imagePath: string,
  colorsArray: string[],
}

export default function Home({ imagePath, colorsArray }: Props) {
  return (
    <>
      <Head>
        <title>Filipe Montanari Soccol - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={imagePath} />
      </Head>
      <main className={styles.main}>
        <div className={styles.holder}>
          <div className={styles.wavy}>
            <a className={styles.socialIcons}><Image src='/github.svg' alt='github' width={32} height={32} /></a>
            <a className={styles.socialIcons}><Image src='/linkedin.svg' alt='linkedin' width={32} height={32} /></a>
            <a className={styles.socialIcons}><Image src='/twitter.svg' alt='twitter' width={32} height={32} /></a>
          </div>
          <h1 className={styles.title}>Filipe Montanari Soccol</h1>
        </div>
        <hr className="m1" />
        <div className={styles.holder2}>
          <div className={styles.bio}>
            <p>Senior Developer with extensive experience in web and game development, creative and excellent team player with a track record of success in high-impact projects and team leadership.</p>
            <div className={styles.bioItem}>Skills</div>
            <div className={styles.bioItem}>Projects</div>
            <div className={styles.bioItem}>Awards</div>
          </div>
          <div className={styles.imageHolder}>
            <div className={styles.image}></div>
          </div>
        </div>
        <div className={styles.sectionTitle}>
          <div><h2>Skills</h2></div>
          <div><hr /></div>
        </div>
        <div className={styles.sectionSkills}>
          <div>
            <h3>Front-end</h3>
            <ul>
              <li>Frameworks: React, Next, Vue, Vite, Gatsby</li>
              <li>Styles: CSS, Bootstrap, Tailwind</li>
              <li>Test: Jest, Mocha, Chai</li>
              <li>Providers: Web3, Ethers</li>
              <li>Decentralized services integration</li>
            </ul>
          </div>
          <div>
            <h3>Back-end</h3>
            <ul>
              <li>Node, Typescript</li>
              <li>Smart-contract: Truffle, Hardhat, Solidity</li>
            </ul>
          </div>
          <div>
            <h3>Management</h3>
            <ul>
              <li>Project Planning</li>
              <li>Team management: Asana, Jira, Git</li>
              <li>Quick learner of new development tools and methods</li>
            </ul>
          </div>
          <div>
            <h3>Front-end</h3>
            <ul>
              <li>Frameworks: React, Next, Vue, Vite, Gatsby</li>
              <li>Styles: CSS, Bootstrap, Tailwind</li>
              <li>Test: Jest, Mocha, Chai</li>
              <li>Providers: Web3, Ethers</li>
              <li>Decentralized services integration</li>
            </ul>
          </div>
          <div>
            <h3>Back-end</h3>
            <ul>
              <li>Node, Typescript</li>
              <li>Smart-contract: Truffle, Hardhat, Solidity</li>
            </ul>
          </div>
          <div>
            <h3>Management</h3>
            <ul>
              <li>Project Planning</li>
              <li>Team management: Asana, Jira, Git</li>
              <li>Quick learner of new development tools and methods</li>
            </ul>
          </div>
        </div>
        <div className={styles.sectionTitle}>
          <div><h2>Projects</h2></div>
          <div><hr /></div>
        </div>
        <div className={styles.sectionAwards}>

        </div>
      </main>
    </>
  )
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API

  const size = 200
  const squareSize = size / 8;
  let svgString = `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 200 200">`;

  const colors = [

    '#0C0A14',
    '#221F22',
    '#4B4538',
    '#FFFFD1',
    '#FFBB01',
  ];

  for (let i = 0; i < 8; i++) {
    for (let j = 0; j < 8; j++) {
      const rect = `<rect
        x="${j * squareSize}" 
        y="${i * squareSize}"
        width="${squareSize}"
        height="${squareSize}"
        fill="${colors[parseInt((Math.random() * 5).toString())]}"
        /> `;
      svgString += rect;
    }
  }

  svgString += "</svg>"
  const base64String = Buffer.from(svgString).toString('base64');
  // Pass data to the page via props
  return { props: { imagePath: `data:image/svg+xml;base64,${base64String}`, colorsArray: colors } }
}