import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'

import awards from '@/public/awards.png'
import projects from '@/public/projects.png'
import skills from '@/public/skills.png'
import { useEffect, useState } from 'react'


interface Props {
  imagePath: string,
  colorsArray: string[],
}

export default function Home({ imagePath, colorsArray }: Props) {

  const [selectedSection, setSelectedSection] = useState<number>(0);
  const [timer, setTimer] = useState<NodeJS.Timer | undefined>();

  useEffect(() => {
    setTimer(setInterval(() => {
      setSelectedSection((prev) => (prev + 1) % 3 + 1)
    }, 2000))
    return () => {
      setTimer(undefined)
      clearInterval(timer)
    }
  }, [])

  const setSelection = (index: number) => {
    setSelectedSection(index)
    clearInterval(timer)
    setTimer(undefined)
  }

  return (
    <>
      <Head>
        <title>Filipe Montanari Soccol - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={imagePath} />
      </Head>
      <main className={styles.main}>
        <div className={styles.holder}>
          <div className={styles.socialBig}>
            <a className={styles.socialIcons}><Image src='/github.svg' alt='github' width={32} height={32} /></a>
            <a className={styles.socialIcons}><Image src='/linkedin.svg' alt='linkedin' width={32} height={32} /></a>
            <a className={styles.socialIcons}><Image src='/twitter.svg' alt='twitter' width={32} height={32} /></a>
          </div>
          <h1 className={styles.title}>Filipe Montanari Soccol</h1>
          <div className={styles.socialSmall}>
            <a className={styles.socialIcons}><Image src='/github.svg' alt='github' width={32} height={32} /></a>
            <a className={styles.socialIcons}><Image src='/linkedin.svg' alt='linkedin' width={32} height={32} /></a>
            <a className={styles.socialIcons}><Image src='/twitter.svg' alt='twitter' width={32} height={32} /></a>
          </div>
        </div>
        <hr className="m1" />
        <div className={styles.holder2}>
          <div className={styles.bio}>
            <p>Senior Developer with extensive experience in web and game development, creative and excellent team player with a track record of success in high-impact projects and team leadership.</p>
            <div className={`${styles.bioItem} ${selectedSection == 1 ? styles.active : ''}`} onMouseEnter={() => setSelection(1)}>Skills</div>
            <div className={`${styles.bioItem} ${selectedSection == 2 ? styles.active : ''}`} onMouseEnter={() => setSelection(2)}>Projects</div>
            <div className={`${styles.bioItem} ${selectedSection == 3 ? styles.active : ''}`} onMouseEnter={() => setSelection(3)}>Awards</div>
          </div>
          <div className={`${styles.imageHolder}`}>
            <div className={`${styles.holderEffect} ${selectedSection == 1 ? styles.active : ''}`}>
              <div className={`${styles.backgroundImage} ${styles.imageThree}  ${selectedSection == 1 ? styles.active : ''}`}></div>
              <Image className={`${styles.foregroundImage}  ${selectedSection == 1 ? styles.active : ''}`} src={skills} alt='Title' height={500}></Image>
            </div>
            <div className={`${styles.holderEffect} ${selectedSection == 2 ? styles.active : ''}`}>
              <div className={`${styles.backgroundImage} ${styles.imageTwo} ${selectedSection == 2 ? styles.active : ''}`}></div>
              <Image className={`${styles.foregroundImage}  ${selectedSection == 2 ? styles.active : ''}`} src={projects} alt='Title' height={500}></Image>
            </div>
            <div className={`${styles.holderEffect} ${selectedSection == 3 ? styles.active : ''}`}>
              <div className={`${styles.backgroundImage} ${styles.imageOne}  ${selectedSection == 3 ? styles.active : ''}`}></div>
              <Image className={`${styles.foregroundImage}  ${selectedSection == 3 ? styles.active : ''}`} src={awards} alt='Title' height={500}></Image>
            </div>
          </div>
        </div>
        <div className={styles.sectionTitle}>
          <div><h2>Skills</h2></div>
          <div><hr /></div>
        </div>
        <div className={styles.sectionSkills}>
          <div>
            <h3>Front-end</h3>
            <ul>
              <li>Frameworks: React, Next, Vue, Vite, Gatsby</li>
              <li>Styles: CSS, Bootstrap, Tailwind</li>
              <li>Test: Jest, Mocha, Chai</li>
              <li>Providers: Web3, Ethers</li>
              <li>Decentralized services integration</li>
            </ul>
          </div>
          <div>
            <h3>Back-end</h3>
            <ul>
              <li>Node, Typescript</li>
              <li>Smart-contract: Truffle, Hardhat, Solidity</li>
            </ul>
          </div>
          <div>
            <h3>Management</h3>
            <ul>
              <li>Project Planning</li>
              <li>Team management: Asana, Jira, Git</li>
              <li>Quick learner of new development tools and methods</li>
            </ul>
          </div>
          <div>
            <h3>Front-end</h3>
            <ul>
              <li>Frameworks: React, Next, Vue, Vite, Gatsby</li>
              <li>Styles: CSS, Bootstrap, Tailwind</li>
              <li>Test: Jest, Mocha, Chai</li>
              <li>Providers: Web3, Ethers</li>
              <li>Decentralized services integration</li>
            </ul>
          </div>
          <div>
            <h3>Back-end</h3>
            <ul>
              <li>Node, Typescript</li>
              <li>Smart-contract: Truffle, Hardhat, Solidity</li>
            </ul>
          </div>
          <div>
            <h3>Management</h3>
            <ul>
              <li>Project Planning</li>
              <li>Team management: Asana, Jira, Git</li>
              <li>Quick learner of new development tools and methods</li>
            </ul>
          </div>
        </div>
        <div className={styles.sectionTitle}>
          <div><h2>Projects</h2></div>
          <div><hr /></div>
        </div>
        <div className={styles.sectionAwards}>

        </div>
      </main>
    </>
  )
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API

  const size = 200
  const squareSize = size / 8;
  let svgString = `<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 200 200">`;

  const colors = [

    '#0C0A14',
    '#221F22',
    '#4B4538',
    '#FFFFD1',
    '#FFBB01',
  ];

  for (let i = 0; i < 8; i++) {
    for (let j = 0; j < 8; j++) {
      const rect = `<rect
        x="${j * squareSize}" 
        y="${i * squareSize}"
        width="${squareSize}"
        height="${squareSize}"
        fill="${colors[parseInt((Math.random() * 5).toString())]}"
        /> `;
      svgString += rect;
    }
  }

  svgString += "</svg>"
  const base64String = Buffer.from(svgString).toString('base64');
  // Pass data to the page via props
  return { props: { imagePath: `data:image/svg+xml;base64,${base64String}`, colorsArray: colors } }
}